spring:
  servlet:
    multipart:
      max-file-size: 3MB
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/inrice_db_rfs?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: zms123456
      usernamedriver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
